### ISSUE TITLE
Error using template

### ISSUE THREAD

**Issue by hurtn** [Azure-Samples/cognitive-search-templates#3]
Hello, I receive this error after specifying connection parameters:

Feedback Type:
Frown (Error)

Error Message:
The database compatibility level of 1465 is below the minimal compatability level of 1480 needed for [table 'Document'].[partition 'Document-00520621-884d-4a0e-b737-eddffb05e15c' in table 'Document']::[QueryGroup] at PowerBI mode.

**Comment by HeidiSteen** [comment]
Closing this issue as we couldn't reproduce it.
